spring:
  data:
    mongodb:
      host: localhost
      port: 8084
      database: learn


  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local




