server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/library-db
    username: postgres
    password: postgres
  sql:
    init:
      mode: ALWAYS
      #data-locations: data.sql
      #schema-locations: schema.sql

  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
