server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 8084
      database: learn

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
