server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      #data-locations: data.sql
      #schema-locations: schema.sql

  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

